export { default as MainPage } from './MainPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as HomePage } from './HomePage';
export { default as SearchPage } from './SearchPage';
export { default as UploadPage } from './UploadPage';
export { default as FollowPage } from './FollowPage';
export { default as ProfilePage } from './ProfilePage';
export { default as CommentPage } from './CommentPage';